$schema: https://json-schema.org/draft/2020-12/schema
title: Tasks Schema
type: object
properties:
  tasks:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          pattern: ^T-\d{3,}$
        epico:
          type: string
        tarefa:
          type: string
        descricao:
          type: string
        ca:
          type: string
        dep:
          type: string
        area:
          type: string
        inputs:
          type: string
        prioridade:
          type: string
        status:
          type: string
          enum:
          - em_progreso
          - em_espera
          - teste
          - finalizada
        estimativa:
          type: string
      required:
      - id
      - tarefa
      - status
required:
- tasks
