schema:
  version: "2.0"
  description: >
    Modelo narrativo e técnico para a engenharia de requisitos.
    Define como as histórias humanas se transformam em requisitos formais.

  components:
    stories:
      description: "Histórias e intenções originais, registradas em linguagem natural."
      format: "Markdown"
      fields:
        - id
        - title
        - context
        - narrative
        - pain_points
        - expected_value
        - validation_questions
        - updated_at

    functional:
      description: "Traduções formais de histórias para comportamentos do sistema."
      format: "YAML"
      fields:
        - id
        - derived_from (story_id)
        - title
        - description
        - actors
        - preconditions
        - flow
        - exceptions
        - acceptance_criteria
        - status
        - updated_at

    non_functional:
      description: "Requisitos qualitativos, éticos e técnicos de longo ciclo."
      format: "YAML"
      fields:
        - id
        - title
        - principle
        - metrics
        - rationale
        - scope
        - updated_at

  lifecycle:
    story_to_functional: "Quando uma história é validada, ela gera 1..N requisitos funcionais."
    functional_to_tasks: "Cada requisito funcional é desdobrado em tarefas concretas."
    non_functional_to_decision: "Requisitos não-funcionais influenciam ADRs e arquitetura."
